name: Update
on:
  workflow_dispatch:
  schedule:
  - cron: 0 0 * * 3
jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Fetch deps
        run: yarn install --non-interactive
      - name: Update lit to latest version
        run: |
          yarn upgrade --latest --exact lit
          yarn upgrade --latest @lit/localize
          yarn upgrade --latest @lit-labs/motion
          yarn upgrade --latest @lit-labs/react
          yarn upgrade --latest @lit-labs/ssr-client
          yarn upgrade --latest @lit-labs/task
      - name: Update package version
        run: |
          VERSION=`jq -r ".dependencies.lit" package.json`
          jq ".version=\"$VERSION\"" package.json > out.json
          mv -f out.json package.json
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Check if there's a new version
        run: |
          git diff
          git diff-index --exit-code HEAD | true
          CHANGED=`git diff-index --exit-code HEAD | wc -l`
          echo "CHANGED=${CHANGED}" >> $GITHUB_ENV
          echo "Changed status: ${CHANGED}"
      - name: Build
        if: ${{ env.CHANGED != 0 }}
        run: |
          yarn exec -- rollup -c
      - name: Push changes
        if: ${{ env.CHANGED != 0 }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Version bump to ${{ env.VERSION }}"
          tagging_message: "${{ env.VERSION }}"
          add_options: "--update"
      - name: Publish new NPM
        if: ${{ env.CHANGED != 0 }}
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
